{% set name = "cmarkgfm" %}
{% set version = "2024.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmarkgfm-{{ version }}.tar.gz
  sha256: a208c1726e12ba385125cef2c6d375c41c5dea4cc2673a77af712b1dbf074e90

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vvv 

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - setuptools
  host:
    - cffi >=1.0.0
    - pip
    - python
    - setuptools
  run:
    - cffi >=1.0.0
    - python

test:
  imports:
    - cmarkgfm

about:
  home: https://github.com/theacodes/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Minimal bindings to GitHub's fork of cmark

extra:
  recipe-maintainers:
    - seanlaw
