{% set name = "cmarkgfm" %}
{% set version = "2025.10.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmarkgfm-{{ version }}.tar.gz
  sha256: c2e242b523043119365bf45a5b399368b0c2b85e6d1349b7b39c6085abd29ad1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - setuptools
  host:
    - cffi >=1.0.0
    - pip
    - python
    - setuptools
  run:
    - cffi >=1.0.0
    - python

test:
  imports:
    - cmarkgfm

about:
  home: https://github.com/theacodes/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Minimal bindings to GitHub's fork of cmark

extra:
  recipe-maintainers:
    - seanlaw
