{% set name = "cmarkgfm" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f20900f16377f2109783ae9348d34bc80530808439591c3d3df73d5c7ef1a00c

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not (win and py27)]
  host:
    - cffi >=1.0.0
    - pip
    - python
    - m2w64-toolchain  # [win and py27]
    - libpython        # [win and py27]
  run:
    - cffi >=1.0.0
    - python
    - m2w64-gcc-libs   # [win and py27]

test:
  imports:
    - cmarkgfm

about:
  home: https://github.com/jonparrott/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Minimal bindings to GitHub's fork of cmark
